### ISSUE TITLE
Enhancement: add sort by (year / journal)

### ISSUE THREAD

**Issue by omrihar** [cgogolin/library#1]
I hope this is a good place to add ideas for the Library app... If not let me know and I'll add it somewhere else. Thanks for the cool app though!

Add sorting by year or by journal (can create buttons for each of the journals that appear). I don't know Java so I can't supply a pull request but I imagine it shouldn't be too difficult to implement.

**Comment by cgogolin** [comment]
Thanks for the feedback. This is indeed rather easy to do. I will look into it.

**Comment by rdiaz02** [comment]
I'd also love to see this implemented (it is easy to ask :-). I find Library to be extremely fast for loading large libraries, but sorting by date (so one can, say, read the last papers added) would be great. Thanks for the library, regardless.

**Comment by cgogolin** [comment]
I am sorry that I haven't found the time to implement this. So many other things that require my attention... Maybe finally over the summer it will happen.
