### ISSUE TITLE
Feature Request: Vertical Scrolling & full view mode

### ISSUE THREAD

**Issue by neolovich** [cgogolin/library#12]
Edit: Wrong App. Sorry.

**Comment by cgogolin** [comment]
The second feature actually exists. It is called Fullscreen and is accessible from the overflow menu.

**Comment by neolovich** [comment]
Yes, i already saw that after posting my comment :-/
But what i have in mind is a feature like it exists in gallery apps for instance. You tap once on the display and the tool bar and the status bar etc. disappears.
