### ISSUE TITLE
Enhancement: add browsing to path

### ISSUE THREAD

**Issue by omrihar** [cgogolin/library#2]
Add a browse dialogue to the location of the bibtex file and to select the directory where the articles are stored (the part which should replace the pdf path in the file fields).

**Comment by cgogolin** [comment]
I am plaing to add this. From Android 4.4 the SAF finally provides a system dialoge for picking files. It will take some time to implement this though.

**Comment by cgogolin** [comment]
This is fully working in 4.4 and above and older versions are increasingly rare, so I close this.
