### ISSUE TITLE
Enhancement: Owncloud support

### ISSUE THREAD

**Issue by rajil** [cgogolin/library#3]
It will be good if it were possible to open bibtex and pdf file from an owncloud instance (webdav).

**Comment by cgogolin** [comment]
The officially recommended way to support cloud storage in newer versions of Android is by the use of storage providers. An upcoming version of Library will allow to pick the BibTeX library file via the system picker UI, allowing it to reside on whichever cloud storage provider you want, provided there is an app that exposes this service as a storage provider. Google drive very nicely does this. Owncloud is in the process of implementing this. The official Dropbox app for example does not.

**Comment by cgogolin** [comment]
Storage provider support is fully implemented for sufficiently recent versions of Android, so I am closing this.
