### ISSUE TITLE
Add relative path management

### ISSUE THREAD

**Issue by MBunel** [cgogolin/library#6]
Hello,

JabRef exports only the name of the pdf (as below), the path of the subfolder containing all the pdf files is specified in the bib file. Can you add the management of files with only the name specified ?

Thanks for your work, the app is really nice.

```
@Article{Zadeh1965,
  author       = {Zadeh, Lotfi Aliasker},
  title        = {Fuzzy sets},
  journaltitle = {Information and control},
  file         = {:Zadeh1965.pdf:PDF}
}

@Comment{jabref-meta: fileDirectory:./PDF;}
```

**Comment by cgogolin** [comment]
This is surely possible. Just so that I understand correctly: There is one `@Comment{jabref-meta: fileDirectory:` per `.bib` file and all the files can then ne found under the location of that path, i.e., the file in your example is under `./PDF/Zadeh1965.pdf`?

Can you explain why the issue you describe is not already solved by the path conversion feature (for SDK_INT < 21) or the new storage access framework enabled "pick a file when opening the first pdf" UI (for SDK_INT >= 21).

**Comment by MBunel** [comment]
Yes it is exactly that, all files are saved in the ./PDF directory. Otherwise, if the folder is not specified ([in the JabRef parameters](http://help.jabref.org/en/DatabaseProperties#override-default-file-directories)), the files are saved in the same folder as the bib file. I think the file field is always of the form ```file = {:fileName.extention:Type} ``` and that the path is never specified in this field.

In my case (Android 7.0, SDK 24), the application crashes, without any error message, after selecting the folder. I tried the same operation by manually modifying the paths. In this case the application works without problems (but only if paths are in unix format  ```file = {:/home/mbunel/Bibliographie/PDF/Zadeh1965.pdf:PDF}```, paths in windows format ```file = {:D:\users\mbunel\Bibliographie\PDF\Zadeh1965.pdf:PDF}``` does not work [probably because of ":" and "\\" in the path]).

**Comment by cgogolin** [comment]
Ah, ok, the crash is the real bug then. I already have an idea what is going wrong. I will fix it as soon as I have some time to spare (probably within the next three to four weeks). Thanks for reporting!

**Comment by cgogolin** [comment]
I will soon release 5.3 on Google Play, which should fix the issue you were describing. Thanks for reporting and please let me know in case you still encounter problems.
