### ISSUE TITLE
Author sort order

### ISSUE THREAD

**Issue by JRInge** [cgogolin/library#8]
When sorting a BibTeX library by Author, I would expect it to sort by the last name of the first listed author.  Instead, Library seems to use a simple alphabetic sort on the whole `author` field.  This gives inconsistent results, depending on the format of the text in the field.

I would expect `author = {Firstname Lastname}` and `author = {Lastname, Firstname}` both to be listed under `L`.  Instead, the first example is listed under `F`.

Information about valid formats for BibTeX author names is online at https://nwalsh.com/tex/texhelp/bibtx-23.html

**Comment by cgogolin** [comment]
Yes, you are correct, this is a limitation of the current implementation. I will keep it in mind for a future update. At least `{First von Last}`, `{von Last, First}`, `{von Last, Jr, First}`, and `{{von Last}, Jr, First}` should all end up under `L`.

**Comment by nivieru** [comment]
I started looking into it. Do you think we should keep the First, Von, Last, Jr parts separately, or just keep a resulting sort-by string, something like Last-First-Jr, in addition to the unedited author string?

**Comment by cgogolin** [comment]
Wow, that's Great!

I don't really see a point is saving them right now. Such functionality would surely be easy to add if needed in the future, but right now it would just wast some memory.

**Comment by JRInge** [comment]
If you kept the parts separate, it might give you more flexibility to add future features like allowing users to customise the sort order or the display format.  That would be more complex, but some people might want to be able to choose whether or not to include the Von part with the Last part for sorting (does van Beethoven sort under V or B?).

**Comment by cgogolin** [comment]
I just looked over the code. Good work!

I have basically just made one structural change. I seemed more logical and more convenient to add the parsing capabilities to `BaseBibtexEntry`. In this way the code for this and the search blob generation are structurally similar.

On the question of whether the individual parts should be saved I don't have a strong opinion. I now added the code that would save them and also geter methods but left them commented out as they are not used at the moment.

I just pushed the code to the ` author_sort_key` branch. Can you please build it and check that I didn't introduce any errors? I will do the same in the coming days.

Thanks for contributing!

**Comment by nivieru** [comment]
Works fine here

**Comment by cgogolin** [comment]
My tests also all passed. I have released this as 6.2. Thanks for the contribution!!!
