### ISSUE TITLE
URL field corrupted by howpublished

### ISSUE THREAD

**Issue by JRInge** [cgogolin/library#9]
If a BibTeX entry has both the `howpublished` field and the `url` field set, the contents of the `howpublished` field seem to be appended onto the URL displayed by Library, causing the hyperlink to fail in the app.

For example, the following BibTex fragment (generated using JabRef), causes Library to display the corrupted URL "`http://www.adelard.com/asce/choosing-asce/cae.htmlOnline`":

    @Misc{CAE,
      author =       {Adelard},
      title =        {Claims, Arguments and Evidence {(CAE)}},
      howpublished = {Online},
      note =         {Accessed 12 Feb 2017.},
      url =          {http://www.adelard.com/asce/choosing-asce/cae.html}
    }

This doesn't seem to happen if the `url` field is empty.

**Comment by cgogolin** [comment]
Thanks for reporting! I know what causes this and will fix it very soon.
